# Generated by Django 5.1.6 on 2025-03-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('image', models.URLField()),
            ],
        ),
    ]
